FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json 

RUN bun install

COPY ./packages ./packages
COPY ./apps/web ./apps/web

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL} 

RUN bun run db:generate
RUN bun run build

EXPOSE 3000 

CMD ["bun", "run", "start:web"] 